# Generated by Django 5.2.4 on 2025-08-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dilyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/'),
        ),
    ]
