# Generated by Django 5.2.4 on 2025-09-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dilyapp', '0005_alter_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
